# Numpy - Refresh

In [43]:
import numpy as np
import pandas as pd

## 1. Array Creation
#### 1.1 Conversion from other Python structures (i.e. lists and tuples)

In [ ]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

- signed dtype
    - np.int8
    - np.int16
    - np.int32
    - np.int64
- unsigned dtype
    - np.uint8
    - np.uint16
    - np.uint32
    - np.uint64

In [4]:
#signed
a = np.array([127, 128, 129], dtype=np.int8)
a

array([ 127, -128, -127], dtype=int8)

In [5]:
#unsigned
a = np.array([127, 128, 129], np.uint8)
a

array([127, 128, 129], dtype=uint8)

In [6]:
a = np.array([127, 128, 129], dtype=np.uint8)
a

array([127, 128, 129], dtype=uint8)

#### 1.2 Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
- There are over 40 built-in functions for creating arrays 

In [7]:
#1D
# arange(start, stop, step)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [11]:
# np.linspace(start, stop, number_of_elements)
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [12]:
# 2D
np.eye(3) # Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.diag([1, 2, 3]) #Diagonal Matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [15]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

In [16]:
#vander(x, n) defines a Vandermonde matrix
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [17]:
#ndarray
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

#### 1.3 Replicating, joining, or mutating existing arrays

In [21]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [22]:
# copy
b = a.copy()
b

array([1, 2, 3, 4])

In [23]:
# hstack
np.hstack((a,b))

array([1, 2, 3, 4, 1, 2, 3, 4])

In [24]:
# vstack
np.vstack((a,b))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [33]:
# column_stack
np.column_stack((a,b))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [35]:
# row_stack
np.row_stack((a,b))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [36]:
# block
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
ABCD = np.block([[A, B], [C, D]])
ABCD

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [28]:
ABCD[0:2, 0:2]

array([[1., 1.],
       [1., 1.]])

In [30]:
ABCD[0:2, 2:4]

array([[1., 0.],
       [0., 1.]])

In [31]:
ABCD[2:4, 0:2]

array([[0., 0.],
       [0., 0.]])

In [38]:
ABCD[2:4, 2:4]

array([[-3.,  0.],
       [ 0., -4.]])

#### 1.4 Reading arrays from disk, either from standard or custom formats

In [42]:
# .csv/.txt
arr = np.loadtxt('abc.txt', delimiter = ',', skiprows = 1)
arr

array([[0., 0.],
       [1., 1.],
       [2., 4.],
       [3., 9.]])

In [47]:
# pandas to numpy
pd.DataFrame({"A": [1, 2], 
              "B": [3, 4]}).to_numpy()

array([[1, 3],
       [2, 4]], dtype=int64)

In [48]:
# Numpy to Pandas
arr = np.array([[11,22,33],[44,55,66]])
df1 = pd.DataFrame(
    arr, columns = ['Column_A','Column_B','Column_C'])
df1

Column_A  Column_B  Column_C
0        11        22        33
1        44        55        66

#### 1.5 Creating arrays from raw bytes through the use of strings or buffers
- np.fromfile(file, dtype=float, count=-1, sep='', offset=0, *, like=None)

#### 1.6 Use of special library functions (e.g., random)
- SciPy, 
- Pandas, &
- OpenCV

# 2. Indexing

In [49]:
x = np.arange(10)

In [50]:
x[2]

2

In [51]:
x[-2]

8

In [53]:
x.shape = (2, 5)
x[1, 3]

8

In [54]:
x[0]

array([0, 1, 2, 3, 4])

In [55]:
x[0][2]

2

In [56]:
x[0, 2]

2

In [61]:
x = x.flatten()
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# slice --> (constructed by start:stop:step
x[1:7:2]

array([1, 3, 5])

In [62]:
x[-2:10]

array([8, 9])

In [63]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [64]:
x[5:]

array([5, 6, 7, 8, 9])

In [70]:
#columns
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [71]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [75]:
x[..., 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
x[:, :, 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
# newaxis is an alias for None
# expand the dimensions of the resulting selection by 
# one unit-length dimension
x[:, np.newaxis, :, :].shape

(2, 1, 3, 1)

In [77]:
x[:, None, :, :].shape

(2, 1, 3, 1)

In [78]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [79]:
x[:, np.newaxis] + x[np.newaxis, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [80]:
x[:, None] + x[None, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [81]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [82]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

In [83]:
x[np.array([3, 3, -3, 8])]

array([7, 7, 4, 2])

In [85]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [86]:
y[np.array([0, 2, 4]), np.array([0, 1, 2])]

array([ 0, 15, 30])

In [87]:
y[np.array([0, 2, 4]), 1]

array([ 1, 15, 29])

In [88]:
y[np.array([0, 2, 4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [90]:
y[:,np.array([0, 2, 4])]

array([[ 0,  2,  4],
       [ 7,  9, 11],
       [14, 16, 18],
       [21, 23, 25],
       [28, 30, 32]])

In [92]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [93]:
x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [94]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [96]:
#Broadcasting
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
x[rows[:, np.newaxis], columns]

array([[ 0,  2],
       [ 9, 11]])

In [97]:
x[np.ix_(rows, columns)]

array([[ 0,  2],
       [ 9, 11]])

In [98]:
#Boolean Indexing
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)]

array([1., 2., 3.])

In [100]:
x = np.array([1., -1., -2., 3])
x[x < 0] += 20
x

array([ 1., 19., 18.,  3.])

In [101]:
# Mask
x = np.arange(35).reshape(5, 7)
b = x > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [112]:
x = np.array([[0, 1, 1], [1, 1, 1], [2, 2, 1]])
x

array([[0, 1, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [113]:
# Row Sum
x.sum(-1) # or x.sum(1)

array([2, 3, 5])

In [117]:
# Column Sum
x.sum(0)

array([3, 4, 3])

In [104]:
rowsum = x.sum(-1)
rowsum

array([1, 2, 4])

In [103]:
x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

In [105]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = (x.sum(-1) % 2) == 0

In [106]:
columns = [0, 2]
x[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

In [121]:
z = np.arange(81).reshape(3, 3, 3, 3)
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [122]:
indices = (1, 1, 1, 1)
z[indices]

40

In [119]:
indices = (1, 1, 1, slice(0, 2))  # same as [1, 1, 1, 0:2]
z[indices]

array([39, 40])

In [120]:
indices = (1, Ellipsis, 1)  # same as [1, ..., 1]
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [123]:
z[::-1]

array([[[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]])

In [125]:
z[:,:,1,1]

array([[ 4, 13, 22],
       [31, 40, 49],
       [58, 67, 76]])

In [126]:
z[::-1,:,1,1]

array([[58, 67, 76],
       [31, 40, 49],
       [ 4, 13, 22]])

In [127]:
z[:,::-1,1,1]

array([[22, 13,  4],
       [49, 40, 31],
       [76, 67, 58]])

In [129]:
z[:,:,1,1::-1]

array([[[ 4,  3],
        [13, 12],
        [22, 21]],

       [[31, 30],
        [40, 39],
        [49, 48]],

       [[58, 57],
        [67, 66],
        [76, 75]]])

In [134]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [135]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [132]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [136]:
b[-1]   # the last row. Equivalent to b[-1, :]

array([40, 41, 42, 43])

In [140]:
b[:, -1]   # the last column. Equivalent to b[:, -1]

array([ 3, 13, 23, 33, 43])

In [141]:
for element in b.flat:
    print(element, end=", ")

0, 1, 2, 3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40, 41, 42, 43, 

In [142]:
#shape manipulation
b.shape

(5, 4)

In [143]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [144]:
b.reshape(10, 2)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13],
       [20, 21],
       [22, 23],
       [30, 31],
       [32, 33],
       [40, 41],
       [42, 43]])

In [146]:
b.T  # returns the array, transposed

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

In [147]:
b.T.shape

(4, 5)

In [150]:
b.resize((2, 10))
b

array([[ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32, 33, 40, 41, 42, 43]])

In [152]:
b.reshape(4, -1) #-1 automatically calculated

array([[ 0,  1,  2,  3, 10],
       [11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32],
       [33, 40, 41, 42, 43]])

# 3. I/O With Numpy
### 3.1 Importing data with genfromtxt
- dtype=float is the default for genfromtxt.
- a sequence of types, such as dtype=(int, float, float).
- a comma-separated string, such as dtype="i4,f8,|U3".
- a dictionary with two keys 'names' and 'formats'.
- a sequence of tuples (name, type), such as dtype=[('A', int), ('B', float)].
- an existing numpy.dtype object.

In [153]:
import numpy as np
from io import StringIO

In [154]:
data = u"1, 2, 3\n4, 5, 6"
np.genfromtxt(StringIO(data), delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.]])

In [155]:
data = u"  1  2  3\n  4  5 67\n890123  4"
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [156]:
data = u"123456789\n   4  7 9\n   4567 9"
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

In [157]:
data = u"1, abc , 2\n 3, xxx, 4"
# Without autostrip
np.genfromtxt(StringIO(data), delimiter=",", dtype="|U5")

array([['1', ' abc ', ' 2'],
       ['3', ' xxx', ' 4']], dtype='<U5')

In [158]:
data = u"""#
# Skip me !
# Skip me too !
1, 2
3, 4
5, 6 #This is the third line of the data
7, 8
# And here comes the last line
9, 0
"""
np.genfromtxt(StringIO(data), comments="#", delimiter=",")

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [160]:
data = u"\n".join(str(i) for i in range(10))
np.genfromtxt(StringIO(data),)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [161]:
np.genfromtxt(StringIO(data),
              skip_header=3, skip_footer=5)

array([3., 4.])

In [162]:
data = u"1 2 3\n4 5 6"
np.genfromtxt(StringIO(data), usecols=(0, -1))

array([[1., 3.],
       [4., 6.]])

In [163]:
np.genfromtxt(StringIO(data), usecols=(0, 1, 2))

array([[1., 2., 3.],
       [4., 5., 6.]])

In [164]:
np.genfromtxt(StringIO(data),
              names="a, b, c", usecols=("a", "c"))

array([(1., 3.), (4., 6.)], dtype=[('a', '<f8'), ('c', '<f8')])

In [165]:
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, names="A, B, C")

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [166]:
data = StringIO("So it goes\n#a b c\n1 2 3\n 4 5 6")
np.genfromtxt(data, skip_header=1, names=True)

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [167]:
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, dtype=(int, float, int))

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('f0', '<i4'), ('f1', '<f8'), ('f2', '<i4')])

### 3.2 np.saves/loads
- DateTime Codes: Y, M, W, D, h, m, s, ms

In [194]:
np.datetime64('today') # today's date

numpy.datetime64('2023-04-16')

In [195]:
np.datetime64('now') # timestamp right now 

numpy.datetime64('2023-04-17T00:27:13')

- np.datetime64(datetime.datetime.now()) is more precise (microseconds vs. seconds)

In [197]:
import datetime
np.datetime64('now') == np.datetime64(datetime.datetime.now())

False

In [169]:
np.datetime64(1, 'Y')

numpy.datetime64('1971')

In [170]:
np.datetime64('2005-02-25')

numpy.datetime64('2005-02-25')

In [171]:
np.datetime64()

numpy.datetime64('NaT')

In [179]:
np.arange('2005-02', '2015-03', dtype='datetime64[Y]')

array(['2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014'], dtype='datetime64[Y]')

In [178]:
np.arange('2005-02', '2005-03', dtype='datetime64[M]')

array(['2005-02'], dtype='datetime64[M]')

In [189]:
np.arange('2005-02', '2005-03', dtype='datetime64[W]')

array(['2005-01-27', '2005-02-03', '2005-02-10', '2005-02-17'],
      dtype='datetime64[W]')

In [172]:
np.arange('2005-02', '2005-03', dtype='datetime64[D]')

array(['2005-02-01', '2005-02-02', '2005-02-03', '2005-02-04',
       '2005-02-05', '2005-02-06', '2005-02-07', '2005-02-08',
       '2005-02-09', '2005-02-10', '2005-02-11', '2005-02-12',
       '2005-02-13', '2005-02-14', '2005-02-15', '2005-02-16',
       '2005-02-17', '2005-02-18', '2005-02-19', '2005-02-20',
       '2005-02-21', '2005-02-22', '2005-02-23', '2005-02-24',
       '2005-02-25', '2005-02-26', '2005-02-27', '2005-02-28'],
      dtype='datetime64[D]')

In [192]:
np.arange('2005-02-01', '2005-02-02', dtype='datetime64[h]')

array(['2005-02-01T00', '2005-02-01T01', '2005-02-01T02', '2005-02-01T03',
       '2005-02-01T04', '2005-02-01T05', '2005-02-01T06', '2005-02-01T07',
       '2005-02-01T08', '2005-02-01T09', '2005-02-01T10', '2005-02-01T11',
       '2005-02-01T12', '2005-02-01T13', '2005-02-01T14', '2005-02-01T15',
       '2005-02-01T16', '2005-02-01T17', '2005-02-01T18', '2005-02-01T19',
       '2005-02-01T20', '2005-02-01T21', '2005-02-01T22', '2005-02-01T23'],
      dtype='datetime64[h]')

In [193]:
np.array([0, 1577836800], dtype='datetime64[m]')

array(['1970-01-01T00:00', '4969-12-24T00:00'], dtype='datetime64[m]')

In [173]:
np.array([0, 1577836800], dtype='datetime64[s]')

array(['1970-01-01T00:00:00', '2020-01-01T00:00:00'],
      dtype='datetime64[s]')

In [174]:
np.array([0, 1577836800000]).astype('datetime64[ms]')

array(['1970-01-01T00:00:00.000', '2020-01-01T00:00:00.000'],
      dtype='datetime64[ms]')

In [175]:
np.datetime64('2005') == np.datetime64('2005-01-01')

True

In [176]:
np.datetime64('2010-03-14T15') == np.datetime64('2010-03-14T15:00:00.00')

True

In [180]:
np.timedelta64(20, 'D')

numpy.timedelta64(20,'D')

In [181]:
np.datetime64('2009') + np.timedelta64(20, 'D')

numpy.datetime64('2009-01-21')

In [182]:
np.datetime64('2011-06-15T00:00') + np.timedelta64(12, 'h')

numpy.datetime64('2011-06-15T12:00')

In [183]:
np.timedelta64(1,'W') / np.timedelta64(1,'D')

7.0

In [184]:
np.timedelta64(1,'W') % np.timedelta64(10,'D')

numpy.timedelta64(7,'D')

In [185]:
np.datetime64('nat') - np.datetime64('2009-01-01')

numpy.timedelta64('NaT','D')

In [186]:
a = np.timedelta64(1, 'Y')
a

numpy.timedelta64(1,'Y')

In [187]:
np.timedelta64(a, 'M')

numpy.timedelta64(12,'M')

In [188]:
np.timedelta64(a, 'D')

TypeError: Cannot cast NumPy timedelta64 scalar from metadata [Y] to [D] according to the rule 'same_kind'